name: Replit DB Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        name: Install dependencies
        run: yarn --frozen-lockfile
        run: yarn run buildxw
        run: yarn run test:ci
        env:
          DB_TOKEN: ${{secrets.DB_TOKEN}}
          DB_HOST: ${{secrets.DB_HOST}}