name: Replit DB Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        name: Install dependencies
        run: yarn --frozen-lockfile
        run: yarn run build
        name: Run tests
        run: yarn run test:ci
        env:
          DB_TOKEN: ${{secrets.DB_TOKEN}}
          DB_HOST: ${{secrets.DB_HOST}}